### ISSUE TITLE
Using the simulation in a real experiment

### ISSUE THREAD

**Issue by IvanOstr** [albeco/GatedMiips#1]
Hello,
Firstly, I really enjoyed your code, it is well written and I learned a lot through it.
I would like to perform an experiment and get the trace by myself, so I can know my pulse's phase.
1) Does MIIPS need the spectral amplitude  in order to do the phase restoration? Or it needs only the trace scan itself. I call spectral amplitude the part E(w) in E(w)*exp(i*phi(w))
2) Currently, in order to use the algorithm one has to pass a class of the type LasePulse. What happens if I want to use the algorithm in a real experiment? Must I use this class? 

Thank you, 
Ivan

**Comment by albeco** [comment]
Hello Ivan,
I am glad you found the GatedMiips code useful.

1. For most cases, MIIPS does not need the spectral amplitude for phase restoration. It is usually possible to retrieve the spectral phase with good (<0.1rad) accuracy, by performing several iterations. However, ignoring the spectral amplitude has some drawbacks and it is possible to devise pulses which would mislead the MIIPS algorithm (see for example https://doi.org/10.1364/OE.24.002505)
2. If you want to use the GatedMIIPS algorithm in a real experiment, you can either create a LaserPulse object from the measured laser spectrum, or you can extract the key parts of the algorithm and embed them in your code: e.g. estimateGDD.m extracts the GDD from a trace, and doubleIntegrateGDD.m gives you the spectral phase.

Best,
Alberto

**Comment by albeco** [comment]
Hello Ivan,
I am glad you found the GatedMiips code useful.

For most cases, MIIPS does not need the spectral amplitude for phase restoration. It is usually possible to retrieve the spectral phase with good (<0.1rad) accuracy, by performing several iterations. However, ignoring the spectral amplitude has some drawbacks and it is possible to devise pulses which would mislead the MIIPS algorithm (see for example https://doi.org/10.1364/OE.24.002505)
If you want to use the GatedMIIPS algorithm in a real experiment, you can either create a LaserPulse object from the measured laser spectrum, or you can extract the key parts of the algorithm and embed them in your code: e.g. estimateGDD.m extracts the GDD from a trace, and doubleIntegrateGDD.m gives you the spectral phase.
Best,
Alberto

**Comment by IvanOstr** [comment]
Thank you very much!
I would like to ask you a few more questions regarding the Iterative Miips.
1) In a real experiment - after one iteration you make the SLM apply minus the retrieved phase, and after each iteration you apply minus the sum of the retrieved phases?
2) I'm not sure how to use IterativeGmiips class you have in your code. Can you give me a hint?
3) When doing iterative Miips - does the phase get closer to the real phase with each iteration?
    I have tried to implement the iterative Miips to retrieve a quadratic phase and got that the phase 
    converges to the real phase in a strange way - (in the file attached you can see that the green line is the best retrieved phase, however in the way some different from expected behaviour occured).
![converging miips phase](https://user-images.githubusercontent.com/39938309/41190150-583f9158-6be2-11e8-857e-ce2686793132.jpg)

Thanks,
Ivan

**Comment by albeco** [comment]
Hello Ivan

1. Yes, that is correct. 
2. The  IterativeGmiips class is a simple wrapper class which stores the results of several iterations. You can add new iterations with the `miips.newIteration()` and access them using the `miips.iterations` property. I added an example file in the examples folder: [Gmiips_2nd_order_iterative.m](https://github.com/albeco/GatedMiips/blob/master/examples/Gmiips_2nd_order_iterative.m)
3. Yes, the retrieved phase should get closer to the true one after each iteration, unless the modulation frequency is too high or the pulse has a strange shape (e.g. fast amplitude oscillations or phase steps). See the example above: If it doesn't help just send me the pulse parameters and I will quickly check
![miips_quadratic_phase_retrival](https://github.com/albeco/GatedMiips/blob/master/manual/example_files/Gmiips_2nd_order_iterative_02.png?raw=true)

Best,
Alberto

**Comment by IvanOstr** [comment]
Hello again,
ragarding 3 -  My pulse is actually rather simple. I attach 2 relevant files with the parameters.
    I'm trying to do iterative Miips on the pulse within them.
    I've noticed that if you change 'IterativeGmiips' to 'Gmiips' the first iteration goes well, but in any other case  I can't get any reasonable results.

[iterative_miips_test.zip](https://github.com/albeco/GatedMiips/files/2090724/iterative_miips_test.zip)

Another question -
Have you noticed numerical differences between using fft and inverse fft and conv function when doing the SHG claculation?
I have different results from using both of them, with errors of 1% sometimes between the traces in the Z axis.

Thank you very much,
Ivan

**Comment by albeco** [comment]
Hi,

actually there was a bug in the `newIteration` method of the `iterativeGmiips` class:
In line 40, the scaled property `fitRangeStd` was used instead of the unscaled `fitRange`.  Now it is fixed and your example file seems to work fine. Thanks for reporting the issue!

I haven't noticed numerical differences when calculating the convolution using conv or via Fourier transform. I would suggest to check if you have aliasing when calculating the fft. In matlab you can pass in the number of points as second argument in the `fft` function. See for example: [the numerical recipes](http://www.aip.de/groups/soe/local/numres/bookfpdf/f13-1.pdf)

Best,
Alberto

**Comment by IvanOstr** [comment]
Thanks for the fix and link! I will definitely check the link out.
Also, should one use iterations with Gmiips or Miips algorithm? In your file it is Miips.

Ivan

**Comment by albeco** [comment]
You are welcome.
You can use iterations with either Miips or GMiips.
I just updated the example file (`Gmiips_2nd_order_iterative.m`) to include both.

Best,
Alberto

**Comment by IvanOstr** [comment]
I would like to ask you another thing:
I've got a trace from the SLM without putting an extra phase, just to know the chirp.
Unfortunately the 'traceMask' in estimateGDD doesn't cut one streak from the trace as it should:
1. Multiple streaks are cut instead of one.
2. As I understand, tau is the slope of the line, and we can the slope of the cut is different from the streak ones.
3. The width of the cut is too big. 

[estimateGDD_parameters_and_traces.zip](https://github.com/albeco/GatedMiips/files/2099563/estimateGDD_parameters_and_traces.zip)
My pulse parameters are - 
lambda0 ~ 1515, tau =0.8e-13, fwhm ~ 20 nm, pulse length ~100 fs.
I attach the trace figure, trace parameters from a break point in estimateGDD (before cutting with traceMask), and the way the streak is cutted.
I ran from -2pi to 2pi with resolution of 100.

Can you give me a hint why it doesn't get the streak as it should?

Appreciating you help,
Ivan

**Comment by albeco** [comment]
Hi,
are you sure that in the experiment tau was really 80fs? it seems to me more like 800fs. I run GMiips on your trace and I got this (assuming tau = 800fs and that the trace was recorded without gate), which seems to be quite resonable
![untitled](https://user-images.githubusercontent.com/13620323/41379907-98e5bfaa-6f63-11e8-9d73-4fc523d38502.jpg)
Could you please double check the experimental parameters?

thanks
Alberto

**Comment by IvanOstr** [comment]
Good morning,
I'll check about the pulse duration really soon, however can you please send me the code you have used to cut the trace that way? Is changing the tau (in estimateGDD) in the parameters I sent you the only change you've made?

edit: Yes i'm quite sure it is less then 250 fms (from product specification), and according to some 
        measurements we did it is around 100 fms.
        tau should be less then pulse duration, so I thought I was ok. 

Thanks,
Ivan

**Comment by albeco** [comment]
here is the code, the other changes are:

1) I defined a dummy laser spectrum (you can plug in the measured one)
2) I interpolated the Miips trace over a linearized frequency axes (both LaserPulse and GMiips classes expect linear scales in time and frequency)

[test_miips_streak_ivan.m.zip](https://github.com/albeco/GatedMiips/files/2100962/test_miips_streak_ivan.m.zip)

edit: actually what I meant that is that the modulation frequency which was used for your Miips trace seems to be 800fs (assuming you have no added chirp, the alternative interpretation would be that you have a huge third order phase contribution, but in that case the modulation amplitude would be too small to get such a trace). Here is a quick linear fit:
![untitled](https://user-images.githubusercontent.com/13620323/41398505-dc39377e-6fb7-11e8-9149-8b9b2849c1e4.jpg)

**Comment by albeco** [comment]
Hi Ivan,
I now close this issue. If you have further questions, you are welcome to open another issue or to write me at albeko@gmail.com
Best
Alberto
